services:
  mysql:
    image: mysql:8.0
    container_name: gelda
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gelda
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

#  redis:
#    image: redis
#    container_name: redis-gelda
#    ports:
#      - "6380:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-gelda
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: gelda
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data: